services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=simas
      - POSTGRES_DB=simas
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5400:5432
